// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { Base64 } from 'js-base64';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} base64
 * @param {MxObject} image
 * @returns {Promise.<boolean>}
 */
export async function Base64DecodeToImage(base64, image) {
	// BEGIN USER CODE
    if (!base64) {
        throw new Error("base64 String should not be empty");
    }
    if (!image) {
        throw new Error("image should not be null");
    }
    const blob = new Blob([Base64.toUint8Array(base64)], { type: "image/png" });
    return new Promise((resolve, reject) => {
        mx.data.saveDocument(image.getGuid(), "camera image", {}, blob, () => resolve(true), reject);
    });
	// END USER CODE
}
