// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package unittesting.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import unittesting.TestExecutionContext;
import unittesting.TestManager;
import unittesting.proxies.Assertion;
import unittesting.proxies.ENUM_UnitTestResult;

public class AssertUsingExpression extends CustomJavaAction<IMendixObject>
{
	private java.lang.String name;
	private java.lang.Boolean expression;
	private java.lang.String failureMessage;
	private java.lang.Boolean stopOnFailure;

	public AssertUsingExpression(IContext context, java.lang.String name, java.lang.Boolean expression, java.lang.String failureMessage, java.lang.Boolean stopOnFailure)
	{
		super(context);
		this.name = name;
		this.expression = expression;
		this.failureMessage = failureMessage;
		this.stopOnFailure = stopOnFailure;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		TestExecutionContext executionContext = TestManager.instance().executionContext();
		Assertion result = executionContext.collectAssertion(getContext(), name, expression, failureMessage);

		if (ENUM_UnitTestResult._2_Failed.equals(result.getResult()) && stopOnFailure)
			throw new TestManager.AssertionException(failureMessage);

		return result.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AssertUsingExpression";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
