// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package unittesting.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import unittesting.ConfigurationManager;
import unittesting.ModelUpdateSubscriber;
import unittesting.TestManager;

public class RegisterModelUpdateSubscriber extends CustomJavaAction<java.lang.Boolean>
{
	public RegisterModelUpdateSubscriber(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (ConfigurationManager.isLocalDevelopment()) {
			ModelUpdateSubscriber logSubscriber = ModelUpdateSubscriber.getInstance();

			Core.registerLogSubscriber(logSubscriber);
			logSubscriber.start();

			return true;
		} else {
			LOG.debug("Did not subscribe to model updates, not in local development");
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RegisterModelUpdateSubscriber";
	}

	// BEGIN EXTRA CODE
	private static final ILogNode LOG = ConfigurationManager.LOG;
	// END EXTRA CODE
}
