// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package unittesting.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import unittesting.TestManager;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class UpdateTestSuiteCountersAndResult extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __testSuite;
	private unittesting.proxies.TestSuite testSuite;

	public UpdateTestSuiteCountersAndResult(IContext context, IMendixObject testSuite)
	{
		super(context);
		this.__testSuite = testSuite;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.testSuite = this.__testSuite == null ? null : unittesting.proxies.TestSuite.initialize(getContext(), __testSuite);

		// BEGIN USER CODE
		TestManager.instance().updateTestSuiteCountersAndResult(getContext(), testSuite, true);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UpdateTestSuiteCountersAndResult";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
